elasticsearch:
    url: https://<ELASTICSEARCH_HOST>:443 # The scheme and port are required
    username: <USERNAME>
    password: <PASSWORD>
index: <INDEX> # Optional - see `--index` and `--auto-index`
